// src/app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import NavLink from "@/components/nav-link";
import { NavItems } from "@/types/nav";

export const metadata: Metadata = {
  title: "Next Jam",
  description: "Generated by create next app",
};

const nav: NavItems = [
  { href: "/", label: "Home" },
  { href: "/lab-1", label: "Lab 1" },
  { href: "/lab-2", label: "Lab 2" },
  { href: "/lab-3", label: "Lab 3" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="border-b">
          <div className="shell flex items-center justify-between py-4">
            <h1 className="text-2xl font-bold">Next Jam</h1>
            <nav className="flex gap-2">
              {nav.map((item) => (
                <NavLink key={item.href} href={item.href} label={item.label} />
              ))}
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
